package dev.negotex.apt.codegen;

import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.TypeSpec;

import javax.annotation.processing.Filer;
import javax.annotation.processing.Messager;
import javax.tools.Diagnostic;
import java.io.IOException;

/**
 * Writes generated Java source files via the annotation processing {@link Filer}.
 *
 * <p>Wraps JavaPoet's {@link JavaFile} writing to handle {@link IOException} uniformly
 * and emit a single error message on failure rather than propagating checked exceptions
 * through generator code.
 */
public final class CodeWriter {

    private final Filer filer;
    private final Messager messager;

    public CodeWriter(Filer filer, Messager messager) {
        this.filer = filer;
        this.messager = messager;
    }

    /**
     * Write a generated type spec as a Java source file in the given package.
     *
     * @param packageName the target package
     * @param typeSpec    the generated type to write
     * @return true if the file was written successfully, false on error
     */
    public boolean write(String packageName, TypeSpec typeSpec) {
        JavaFile javaFile = JavaFile.builder(packageName, typeSpec)
                .addFileComment("Generated by negotex-annotation-processor — do not edit")
                .indent("    ")
                .build();
        try {
            javaFile.writeTo(filer);
            return true;
        } catch (IOException e) {
            messager.printMessage(Diagnostic.Kind.ERROR,
                    "Failed to write generated file '" + typeSpec.name + "': " + e.getMessage());
            return false;
        }
    }
}
