package dev.negotex.manifest;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import com.fasterxml.jackson.dataformat.yaml.YAMLGenerator;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

/**
 * The complete runtime manifest for one runtime instance.
 *
 * <p>Generated by the process compiler from {@code process.yaml} and
 * {@code deployment.yaml}. Consumed by the runtime at startup — the
 * runtime never reads the source process definition directly.
 *
 * <p>Contains exactly what one runtime instance needs to start:
 * <ul>
 *   <li>Process identity and version</li>
 *   <li>Its own runtime instance descriptor</li>
 *   <li>The nodes it is responsible for (subset of the full process graph)</li>
 *   <li>All edges — including edges to/from nodes on other runtime instances,
 *       since this instance must produce to and consume from those topics</li>
 *   <li>Infrastructure endpoints</li>
 * </ul>
 *
 * @see <a href="https://negotex.dev/docs/adr/ADR-022-Runtime-Manifest.md">ADR-022</a>
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record RuntimeManifest(

        /** Process identifier. e.g. {@code "loan-application"} */
        String processId,

        /** Structural process version. e.g. {@code "1.3.0"} */
        String processVersion,

        /**
         * When true, all nodes must declare {@code consistency: deterministic}.
         * Enables full process replay verification (ADR-030).
         */
        boolean auditCertificationMode,

        /**
         * Default maximum retry attempts for all nodes.
         * Individual nodes may override via {@link NodeManifest#maxRetries()}.
         */
        int defaultMaxRetries,

        /** This runtime instance's descriptor. */
        RuntimeInstanceManifest runtimeInstance,

        /**
         * Nodes assigned to this runtime instance.
         * Keyed by node ID for O(1) lookup during Kafka consumer dispatch.
         */
        Map<String, NodeManifest> nodes,

        /**
         * All edges in the process — including edges between nodes on different
         * runtime instances. Keyed by edge ID.
         * The runtime needs the full edge set to resolve topic names for
         * both incoming (consume) and outgoing (produce) edges.
         */
        Map<String, EdgeManifest> edges,

        /** Infrastructure endpoint configuration. */
        InfrastructureManifest infrastructure
) {

    // ── Serialisation ─────────────────────────────────────────────────────────

    private static final ObjectMapper YAML_MAPPER = new ObjectMapper(
            new YAMLFactory()
                    .disable(YAMLGenerator.Feature.WRITE_DOC_START_MARKER)
                    .enable(YAMLGenerator.Feature.MINIMIZE_QUOTES)
    );

    /**
     * Deserialise a {@code RuntimeManifest} from a YAML file.
     *
     * @param path path to the manifest YAML file
     * @return the deserialised manifest
     * @throws IOException if the file cannot be read or parsed
     */
    public static RuntimeManifest fromYaml(Path path) throws IOException {
        try (InputStream in = Files.newInputStream(path)) {
            return YAML_MAPPER.readValue(in, RuntimeManifest.class);
        }
    }

    /**
     * Serialise this manifest to a YAML file.
     *
     * @param path destination path
     * @throws IOException if the file cannot be written
     */
    public void toYaml(Path path) throws IOException {
        try (OutputStream out = Files.newOutputStream(path)) {
            YAML_MAPPER.writeValue(out, this);
        }
    }

    // ── Convenience lookups ───────────────────────────────────────────────────

    /**
     * Find the node manifest for the given node ID.
     *
     * @throws IllegalArgumentException if the node is not assigned to this runtime
     */
    public NodeManifest node(String nodeId) {
        NodeManifest node = nodes.get(nodeId);
        if (node == null) {
            throw new IllegalArgumentException(
                    "Node '%s' is not assigned to runtime instance '%s'"
                            .formatted(nodeId, runtimeInstance.name()));
        }
        return node;
    }

    /**
     * Find the edge manifest for the given edge ID.
     *
     * @throws IllegalArgumentException if the edge is not known to this runtime
     */
    public EdgeManifest edge(String edgeId) {
        EdgeManifest edge = edges.get(edgeId);
        if (edge == null) {
            throw new IllegalArgumentException(
                    "Edge '%s' is not known to runtime instance '%s'"
                            .formatted(edgeId, runtimeInstance.name()));
        }
        return edge;
    }

    /**
     * Resolve the Kafka topic name for the given edge ID.
     */
    public String topicName(String edgeId) {
        return edge(edgeId).topicName();
    }

    /**
     * Return the list of node IDs assigned to this runtime instance.
     */
    public List<String> assignedNodeIds() {
        return runtimeInstance.nodeIds();
    }
}
